//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Logica.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPrueba {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPrueba() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveShopping.Logica.UnitTest.RecursosPrueba", typeof(RecursosPrueba).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///	&lt;fittings&gt;
        ///		&lt;fitting name=&quot;breacher - dual td v1.3&quot;&gt;
        ///			&lt;description value=&quot;&quot;/&gt;
        ///			&lt;shipType value=&quot;Breacher&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 0&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 1&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 2&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware qty=&quot;2&quot; slot=&quot;drone bay&quot; type=&quot;Warrior II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 0&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 1&quot; type=&quot;Nan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EveXmlTresNaves {
            get {
                return ResourceManager.GetString("EveXmlTresNaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fitting name=&quot;breacher - dual td v1.3&quot;&gt;
        ///			&lt;description value=&quot;&quot;/&gt;
        ///			&lt;shipType value=&quot;Breacher&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 0&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 1&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 2&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware qty=&quot;2&quot; slot=&quot;drone bay&quot; type=&quot;Warrior II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 0&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 1&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EveXmlUnaNaveNoRoot {
            get {
                return ResourceManager.GetString("EveXmlUnaNaveNoRoot", resourceCulture);
            }
        }
    }
}
