//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Logica.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPrueba {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPrueba() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveShopping.Logica.UnitTest.RecursosPrueba", typeof(RecursosPrueba).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125mm Railgun II	8	Hybrid Weapon	Small	High	40 m3
        ///200mm AutoCannon I	4	Projectile Weapon	Small	High	20 m3
        ///200mm AutoCannon II	1	Projectile Weapon	Small	High	5 m3
        ///Caldari Navy Antimatter Charge S	171	Hybrid Charge	Small		0,43 m3
        ///Caldari Navy Plutonium Charge S	2.380	Hybrid Charge	Small		5,95 m3
        ///Damage Control II	1	Damage Control		Low	5 m3
        ///F-90 Positional Sensor Subroutines	1	Sensor Booster	Small	Medium	5 m3
        ///F85 Peripheral Damage System I	1	Damage Control		Low	5 m3
        ///Faint Warp Disruptor I	1	Warp Scrambler		Med [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets1 {
            get {
                return ResourceManager.GetString("assets1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string assetsFewStations1 {
            get {
                return ResourceManager.GetString("assetsFewStations1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Vexor, Vexor solo PvP]
        ///Damage Control II
        ///Drone Damage Amplifier II
        ///Drone Damage Amplifier II
        ///Energized Adaptive Nano Membrane II
        ///1600mm Reinforced Steel Plates II
        ///
        ///Warp Scrambler II
        ///Stasis Webifier II
        ///Medium Capacitor Booster II, Cap Booster 25
        ///Experimental 10MN Microwarpdrive I
        ///
        ///Small EMP Smartbomb II
        ///Heavy Electron Blaster II, Antimatter Charge M
        ///Heavy Electron Blaster II, Antimatter Charge M
        ///Small Energy Neutralizer II
        ///
        ///Medium Anti-Explosive Pump I
        ///Medium Trimark Armor Pump I
        ///Medium A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFT1 {
            get {
                return ResourceManager.GetString("EFT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///	&lt;fittings&gt;
        ///		&lt;fitting name=&quot;breacher - dual td v1.3&quot;&gt;
        ///			&lt;description value=&quot;&quot;/&gt;
        ///			&lt;shipType value=&quot;Breacher&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 0&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 1&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 2&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware qty=&quot;2&quot; slot=&quot;drone bay&quot; type=&quot;Warrior II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 0&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 1&quot; type=&quot;Nan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EveXmlTresNaves {
            get {
                return ResourceManager.GetString("EveXmlTresNaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fitting name=&quot;breacher - dual td v1.3&quot;&gt;
        ///			&lt;description value=&quot;&quot;/&gt;
        ///			&lt;shipType value=&quot;Breacher&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 0&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 1&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware slot=&quot;hi slot 2&quot; type=&quot;Light Missile Launcher II&quot;/&gt;
        ///			&lt;hardware qty=&quot;2&quot; slot=&quot;drone bay&quot; type=&quot;Warrior II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 0&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;hardware slot=&quot;low slot 1&quot; type=&quot;Nanofiber Internal Structure II&quot;/&gt;
        ///			&lt;ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EveXmlUnaNaveNoRoot {
            get {
                return ResourceManager.GetString("EveXmlUnaNaveNoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Moa, 1]
        ///
        ///Magnetic Field Stabilizer II
        ///Magnetic Field Stabilizer II
        ///Co-Processor II
        ///Damage Control II
        ///
        ///Large Ancillary Shield Booster, Navy Cap Booster 150
        ///Large Ancillary Shield Booster, Navy Cap Booster 150
        ///Warp Scrambler II
        ///Experimental 10MN Microwarpdrive I
        ///Stasis Webifier II
        ///
        ///Heavy Electron Blaster II, Caldari Navy Antimatter Charge M
        ///Heavy Ion Blaster II, Caldari Navy Antimatter Charge M
        ///Heavy Ion Blaster II, Caldari Navy Antimatter Charge M
        ///Heavy Ion Blaster II, Caldari Navy Antimatte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moaFalla {
            get {
                return ResourceManager.GetString("moaFalla", resourceCulture);
            }
        }
    }
}
