//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshChangeLog_Mapping : EntityTypeConfiguration<eshChangeLog>
    {
        public eshChangeLog_Mapping()
        {                        
              this.HasKey(t => t.changeLogID);        
              this.ToTable("eshChangeLog");
              this.Property(t => t.changeLogID).HasColumnName("changeLogID");
              this.Property(t => t.name).HasColumnName("name").IsRequired().HasMaxLength(200);
              this.Property(t => t.version).HasColumnName("version").IsRequired().HasMaxLength(50);
              this.Property(t => t.changes).HasColumnName("changes");
              this.Property(t => t.date).HasColumnName("date");
         }
    }
}
