//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshChangeLog
    {
        public int changeLogID { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public string changes { get; set; }
        public System.DateTime date { get; set; }
    }
}
