//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshEveAccountCharacter_Mapping : EntityTypeConfiguration<eshEveAccountCharacter>
    {
        public eshEveAccountCharacter_Mapping()
        {                        
              this.HasKey(t => t.characterID);        
              this.ToTable("eshEveAccountCharacter");
              this.Property(t => t.accountID).HasColumnName("accountID");
              this.Property(t => t.name).HasColumnName("name").IsRequired().HasMaxLength(250);
              this.Property(t => t.corpName).HasColumnName("corpName").IsRequired().HasMaxLength(250);
              this.Property(t => t.corpTicker).HasColumnName("corpTicker").HasMaxLength(10);
              this.Property(t => t.characterID).HasColumnName("characterID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.eveID).HasColumnName("eveID");
              this.Property(t => t.alliName).HasColumnName("alliName").HasMaxLength(250);
              this.Property(t => t.alliTicker).HasColumnName("alliTicker").HasMaxLength(10);
              this.HasRequired(t => t.eshEveAccount).WithMany(t => t.eshEveAccountCharacters).HasForeignKey(d => d.accountID);
         }
    }
}
