//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshFitting
    {
        public eshFitting()
        {
            this.eshFittingHardwares = new HashSet<eshFittingHardware>();
            this.eshShoppingListFittings = new HashSet<eshShoppingListFitting>();
        }
    
        public int fittingID { get; set; }
        public string name { get; set; }
        public Nullable<int> shipTypeID { get; set; }
        public string description { get; set; }
        public System.DateTime dateCreation { get; set; }
        public double shipVolume { get; set; }
        public double volume { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> urlID { get; set; }
        public string publicID { get; set; }
    
        public virtual ICollection<eshFittingHardware> eshFittingHardwares { get; set; }
        public virtual eshTinyUrlMapping eshTinyUrlMapping { get; set; }
        public virtual invType invType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<eshShoppingListFitting> eshShoppingListFittings { get; set; }
    }
}
