//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshFittingHardware_Mapping : EntityTypeConfiguration<eshFittingHardware>
    {
        public eshFittingHardware_Mapping()
        {                        
              this.HasKey(t => t.fittingHardwareID);        
              this.ToTable("eshFittingHardwares");
              this.Property(t => t.fittingHardwareID).HasColumnName("fittingHardwareID");
              this.Property(t => t.fittingID).HasColumnName("fittingID");
              this.Property(t => t.typeID).HasColumnName("typeID");
              this.Property(t => t.slotID).HasColumnName("slotID");
              this.Property(t => t.positionInSlot).HasColumnName("positionInSlot");
              this.Property(t => t.units).HasColumnName("units");
              this.Property(t => t.volume).HasColumnName("volume");
              this.HasRequired(t => t.eshFitting).WithMany(t => t.eshFittingHardwares).HasForeignKey(d => d.fittingID);
              this.HasRequired(t => t.eshFittingSlot).WithMany(t => t.eshFittingHardwares).HasForeignKey(d => d.slotID);
              this.HasRequired(t => t.invType).WithMany(t => t.eshFittingHardwares).HasForeignKey(d => d.typeID);
         }
    }
}
