//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshFittingSlot_Mapping : EntityTypeConfiguration<eshFittingSlot>
    {
        public eshFittingSlot_Mapping()
        {                        
              this.HasKey(t => t.slotID);        
              this.ToTable("eshFittingSlots");
              this.Property(t => t.slotID).HasColumnName("slotID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.name).HasColumnName("name").IsRequired().HasMaxLength(100);
         }
    }
}
