//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshGroupShoppingListSnapshot
    {
        public int groupShoppingListID { get; set; }
        public int snapshotID { get; set; }
        public string nickName { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual eshGroupShoppingList eshGroupShoppingList { get; set; }
        public virtual eshSnapshot eshSnapshot { get; set; }
    }
}
