//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshGroupShoppingList
    {
        public eshGroupShoppingList()
        {
            this.eshGroupShoppingListSnapshots = new HashSet<eshGroupShoppingListSnapshot>();
        }
    
        public int groupShoppingListID { get; set; }
        public int userID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string publicID { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public int tradeHubID { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual eshTradeHub eshTradeHub { get; set; }
        public virtual ICollection<eshGroupShoppingListSnapshot> eshGroupShoppingListSnapshots { get; set; }
    }
}
