//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshGroupShoppingList_Mapping : EntityTypeConfiguration<eshGroupShoppingList>
    {
        public eshGroupShoppingList_Mapping()
        {                        
              this.HasKey(t => t.groupShoppingListID);        
              this.ToTable("eshGroupShoppingList");
              this.Property(t => t.groupShoppingListID).HasColumnName("groupShoppingListID");
              this.Property(t => t.userID).HasColumnName("userID");
              this.Property(t => t.name).HasColumnName("name").IsRequired().HasMaxLength(50);
              this.Property(t => t.description).HasColumnName("description").HasMaxLength(3990);
              this.Property(t => t.publicID).HasColumnName("publicID").IsRequired().HasMaxLength(50);
              this.Property(t => t.dateCreation).HasColumnName("dateCreation");
              this.Property(t => t.dateUpdate).HasColumnName("dateUpdate");
              this.Property(t => t.tradeHubID).HasColumnName("tradeHubID");
              this.HasRequired(t => t.UserProfile).WithMany(t => t.eshGroupShoppingLists).HasForeignKey(d => d.userID);
              this.HasRequired(t => t.eshTradeHub).WithMany(t => t.eshGroupShoppingLists).HasForeignKey(d => d.tradeHubID);
         }
    }
}
