//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshLog
    {
        public int LogID { get; set; }
        public int Code { get; set; }
        public short Severity { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
