//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshSnapshot_Mapping : EntityTypeConfiguration<eshSnapshot>
    {
        public eshSnapshot_Mapping()
        {                        
              this.HasKey(t => t.snapshotID);        
              this.ToTable("eshSnapshot");
              this.Property(t => t.snapshotID).HasColumnName("snapshotID");
              this.Property(t => t.shoppingListID).HasColumnName("shoppingListID");
              this.Property(t => t.creationDate).HasColumnName("creationDate");
              this.Property(t => t.totalVolume).HasColumnName("totalVolume");
              this.Property(t => t.totalPrice).HasColumnName("totalPrice");
              this.Property(t => t.publicID).HasColumnName("publicID").IsRequired().HasMaxLength(50);
              this.Property(t => t.name).HasColumnName("name").HasMaxLength(100);
              this.Property(t => t.description).HasColumnName("description").HasMaxLength(3990);
              this.Property(t => t.urlID).HasColumnName("urlID");
              this.HasRequired(t => t.eshShoppingList).WithMany(t => t.eshSnapshots).HasForeignKey(d => d.shoppingListID);
              this.HasOptional(t => t.eshTinyUrlMapping).WithMany(t => t.eshSnapshots).HasForeignKey(d => d.urlID);
         }
    }
}
