//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshSnapshotInvType_Mapping : EntityTypeConfiguration<eshSnapshotInvType>
    {
        public eshSnapshotInvType_Mapping()
        {                        
              this.HasKey(t => new {t.snapshotID, t.typeID});        
              this.ToTable("eshSnapshotInvType");
              this.Property(t => t.snapshotID).HasColumnName("snapshotID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.typeID).HasColumnName("typeID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.units).HasColumnName("units");
              this.Property(t => t.unitPrice).HasColumnName("unitPrice");
              this.Property(t => t.volume).HasColumnName("volume");
              this.HasRequired(t => t.eshSnapshot).WithMany(t => t.eshSnapshotInvTypes).HasForeignKey(d => d.snapshotID);
              this.HasRequired(t => t.invType).WithMany(t => t.eshSnapshotInvTypes).HasForeignKey(d => d.typeID);
         }
    }
}
