//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshShoppingListSummInvType
    {
        public int shoppingListID { get; set; }
        public int typeID { get; set; }
        public int delta { get; set; }
    
        public virtual eshShoppingList eshShoppingList { get; set; }
        public virtual invType invType { get; set; }
    }
}
