//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshShoppingList_Mapping : EntityTypeConfiguration<eshShoppingList>
    {
        public eshShoppingList_Mapping()
        {                        
              this.HasKey(t => t.shoppingListID);        
              this.ToTable("eshShoppingLists");
              this.Property(t => t.shoppingListID).HasColumnName("shoppingListID");
              this.Property(t => t.publicID).HasColumnName("publicID").IsRequired().HasMaxLength(50);
              this.Property(t => t.name).HasColumnName("name").HasMaxLength(100);
              this.Property(t => t.description).HasColumnName("description").HasMaxLength(3990);
              this.Property(t => t.dateCreation).HasColumnName("dateCreation");
              this.Property(t => t.readOnlypublicID).HasColumnName("readOnlypublicID").IsRequired().HasMaxLength(50);
              this.Property(t => t.dateUpdate).HasColumnName("dateUpdate");
              this.Property(t => t.tradeHubID).HasColumnName("tradeHubID");
              this.Property(t => t.dateAccess).HasColumnName("dateAccess");
              this.Property(t => t.allowEditForAll).HasColumnName("allowEditForAll");
              this.Property(t => t.userID).HasColumnName("userID");
              this.Property(t => t.urlID).HasColumnName("urlID");
              this.HasOptional(t => t.eshTinyUrlMapping).WithMany(t => t.eshShoppingLists).HasForeignKey(d => d.urlID);
              this.HasRequired(t => t.eshTradeHub).WithMany(t => t.eshShoppingLists).HasForeignKey(d => d.tradeHubID);
              this.HasOptional(t => t.UserProfile).WithMany(t => t.eshShoppingLists).HasForeignKey(d => d.userID);
         }
    }
}
