//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshShoppingListFitting_Mapping : EntityTypeConfiguration<eshShoppingListFitting>
    {
        public eshShoppingListFitting_Mapping()
        {                        
              this.HasKey(t => new {t.shoppingListID, t.fittingID});        
              this.ToTable("eshShoppingListFittings");
              this.Property(t => t.shoppingListID).HasColumnName("shoppingListID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.fittingID).HasColumnName("fittingID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.units).HasColumnName("units");
              this.HasRequired(t => t.eshFitting).WithMany(t => t.eshShoppingListFittings).HasForeignKey(d => d.fittingID);
              this.HasRequired(t => t.eshShoppingList).WithMany(t => t.eshShoppingListFittings).HasForeignKey(d => d.shoppingListID);
         }
    }
}
