//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class eshTradeHub_Mapping : EntityTypeConfiguration<eshTradeHub>
    {
        public eshTradeHub_Mapping()
        {                        
              this.HasKey(t => t.solarSystemID);        
              this.ToTable("eshTradeHubs");
              this.Property(t => t.solarSystemID).HasColumnName("solarSystemID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.HasRequired(t => t.mapSolarSystem).WithOptional(t => t.eshTradeHub);
         }
    }
}
