//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class eshTinyUrlMapping
    {
        public eshTinyUrlMapping()
        {
            this.eshFittings = new HashSet<eshFitting>();
            this.eshShoppingLists = new HashSet<eshShoppingList>();
            this.eshSnapshots = new HashSet<eshSnapshot>();
        }
    
        public int urlId { get; set; }
        public string tinyUrl { get; set; }
        public string finalUrl { get; set; }
        public bool isPermanent { get; set; }
        public Nullable<System.DateTime> lastGivenTime { get; set; }
    
        public virtual ICollection<eshFitting> eshFittings { get; set; }
        public virtual ICollection<eshShoppingList> eshShoppingLists { get; set; }
        public virtual ICollection<eshSnapshot> eshSnapshots { get; set; }
    }
}
