//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class invMarketGroup_Mapping : EntityTypeConfiguration<invMarketGroup>
    {
        public invMarketGroup_Mapping()
        {                        
              this.HasKey(t => t.marketGroupID);        
              this.ToTable("invMarketGroups");
              this.Property(t => t.marketGroupID).HasColumnName("marketGroupID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.parentGroupID).HasColumnName("parentGroupID");
              this.Property(t => t.marketGroupName).HasColumnName("marketGroupName").HasMaxLength(100);
              this.Property(t => t.description).HasColumnName("description").HasMaxLength(3000);
              this.Property(t => t.iconID).HasColumnName("iconID");
              this.Property(t => t.hasTypes).HasColumnName("hasTypes");
         }
    }
}
