//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.eshFittings = new HashSet<eshFitting>();
            this.eshGroupShoppingLists = new HashSet<eshGroupShoppingList>();
            this.eshShoppingLists = new HashSet<eshShoppingList>();
            this.eshEveAccounts = new HashSet<eshEveAccount>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<eshFitting> eshFittings { get; set; }
        public virtual ICollection<eshGroupShoppingList> eshGroupShoppingLists { get; set; }
        public virtual ICollection<eshShoppingList> eshShoppingLists { get; set; }
        public virtual ICollection<eshEveAccount> eshEveAccounts { get; set; }
    }
}
