//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class UserProfile_Mapping : EntityTypeConfiguration<UserProfile>
    {
        public UserProfile_Mapping()
        {                        
              this.HasKey(t => t.UserId);        
              this.ToTable("UserProfile");
              this.Property(t => t.UserId).HasColumnName("UserId");
              this.Property(t => t.UserName).HasColumnName("UserName");
         }
    }
}
