//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Modelo
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class webpages_Roles_Mapping : EntityTypeConfiguration<webpages_Roles>
    {
        public webpages_Roles_Mapping()
        {                        
              this.HasKey(t => t.RoleId);        
              this.ToTable("webpages_Roles");
              this.Property(t => t.RoleId).HasColumnName("RoleId");
              this.Property(t => t.RoleName).HasColumnName("RoleName").IsRequired().HasMaxLength(256);
         }
    }
}

