//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveShopping.Logica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveShopping.Logica.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fitting is already used in this shopping list..
        /// </summary>
        internal static string err_fittigAlreadyUsed {
            get {
                return ResourceManager.GetString("err_fittigAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record of this fitting in our registers.
        /// </summary>
        internal static string err_fittingNoExiste {
            get {
                return ResourceManager.GetString("err_fittingNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not found in the shopping list..
        /// </summary>
        internal static string err_itemNoEnShoppingList {
            get {
                return ResourceManager.GetString("err_itemNoEnShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysed fit contains an item with a name that cant be recognized.
        /// </summary>
        internal static string err_nombreItemAnalizadaNoExiste {
            get {
                return ResourceManager.GetString("err_nombreItemAnalizadaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url/id provided doesnt belong to any list in our database..
        /// </summary>
        internal static string err_notAnyKindOfList {
            get {
                return ResourceManager.GetString("err_notAnyKindOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont seem to be the rightful owner of the element that you want to delete..
        /// </summary>
        internal static string err_notOwner {
            get {
                return ResourceManager.GetString("err_notOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a module in the DNA expression with the wrong format..
        /// </summary>
        internal static string err_notRecognisedDNAFormat {
            get {
                return ResourceManager.GetString("err_notRecognisedDNAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fitting doesn&apos;t have a recognised format..
        /// </summary>
        internal static string err_notRecognisedFormat {
            get {
                return ResourceManager.GetString("err_notRecognisedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysed fit contains an item that doesnt exist..
        /// </summary>
        internal static string err_notRecognisedItemInFitting {
            get {
                return ResourceManager.GetString("err_notRecognisedItemInFitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list doesnt contains the item..
        /// </summary>
        internal static string err_notRecognisedItemInList {
            get {
                return ResourceManager.GetString("err_notRecognisedItemInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided URL is not valid..
        /// </summary>
        internal static string err_providedUrlNotValid {
            get {
                return ResourceManager.GetString("err_providedUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find the shopping list in our acurate archives. Try to create it again..
        /// </summary>
        internal static string err_shoppingLisNoExiste {
            get {
                return ResourceManager.GetString("err_shoppingLisNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The static shopping list doesnt exist in our archives..
        /// </summary>
        internal static string err_staticShoppingListNoExiste {
            get {
                return ResourceManager.GetString("err_staticShoppingListNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t exist in our database..
        /// </summary>
        internal static string err_usuarioNoExiste {
            get {
                return ResourceManager.GetString("err_usuarioNoExiste", resourceCulture);
            }
        }
    }
}
